//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("cms_2Model", "FK_Categories_Templates", "Templates", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CMS.Models.Template), "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS.Models.Category), true)]
[assembly: EdmRelationshipAttribute("cms_2Model", "FK_CategoryRelations_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CMS.Models.Category), "CategoryRelation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS.Models.CategoryRelation), true)]
[assembly: EdmRelationshipAttribute("cms_2Model", "FK_CategoryRelations_Categories1", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CMS.Models.Category), "CategoryRelation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS.Models.CategoryRelation), true)]
[assembly: EdmRelationshipAttribute("cms_2Model", "FK_Links_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CMS.Models.Category), "Link", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS.Models.Link), true)]
[assembly: EdmRelationshipAttribute("cms_2Model", "FK_Pictures_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CMS.Models.Category), "Picture", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS.Models.Picture), true)]
[assembly: EdmRelationshipAttribute("cms_2Model", "FK_Texts_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CMS.Models.Category), "Text", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS.Models.Text), true)]
[assembly: EdmRelationshipAttribute("cms_2Model", "FK_Videos_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CMS.Models.Category), "Video", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS.Models.Video), true)]

#endregion

namespace CMS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cms_2Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cms_2Entities object using the connection string found in the 'cms_2Entities' section of the application configuration file.
        /// </summary>
        public cms_2Entities() : base("name=cms_2Entities", "cms_2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cms_2Entities object.
        /// </summary>
        public cms_2Entities(string connectionString) : base(connectionString, "cms_2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cms_2Entities object.
        /// </summary>
        public cms_2Entities(EntityConnection connection) : base(connection, "cms_2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Link> Links
        {
            get
            {
                if ((_Links == null))
                {
                    _Links = base.CreateObjectSet<Link>("Links");
                }
                return _Links;
            }
        }
        private ObjectSet<Link> _Links;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Picture> Pictures
        {
            get
            {
                if ((_Pictures == null))
                {
                    _Pictures = base.CreateObjectSet<Picture>("Pictures");
                }
                return _Pictures;
            }
        }
        private ObjectSet<Picture> _Pictures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Template> Templates
        {
            get
            {
                if ((_Templates == null))
                {
                    _Templates = base.CreateObjectSet<Template>("Templates");
                }
                return _Templates;
            }
        }
        private ObjectSet<Template> _Templates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Text> Texts
        {
            get
            {
                if ((_Texts == null))
                {
                    _Texts = base.CreateObjectSet<Text>("Texts");
                }
                return _Texts;
            }
        }
        private ObjectSet<Text> _Texts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Video> Videos
        {
            get
            {
                if ((_Videos == null))
                {
                    _Videos = base.CreateObjectSet<Video>("Videos");
                }
                return _Videos;
            }
        }
        private ObjectSet<Video> _Videos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoryRelation> CategoryRelations
        {
            get
            {
                if ((_CategoryRelations == null))
                {
                    _CategoryRelations = base.CreateObjectSet<CategoryRelation>("CategoryRelations");
                }
                return _CategoryRelations;
            }
        }
        private ObjectSet<CategoryRelation> _CategoryRelations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Links EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLinks(Link link)
        {
            base.AddObject("Links", link);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pictures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPictures(Picture picture)
        {
            base.AddObject("Pictures", picture);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Templates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemplates(Template template)
        {
            base.AddObject("Templates", template);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Texts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTexts(Text text)
        {
            base.AddObject("Texts", text);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Videos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideos(Video video)
        {
            base.AddObject("Videos", video);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoryRelations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoryRelations(CategoryRelation categoryRelation)
        {
            base.AddObject("CategoryRelations", categoryRelation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="catID">Initial value of the CatID property.</param>
        /// <param name="catName">Initial value of the CatName property.</param>
        /// <param name="tempID">Initial value of the TempID property.</param>
        public static Category CreateCategory(global::System.Int64 catID, global::System.String catName, global::System.Int64 tempID)
        {
            Category category = new Category();
            category.CatID = catID;
            category.CatName = catName;
            category.TempID = tempID;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CatID
        {
            get
            {
                return _CatID;
            }
            set
            {
                if (_CatID != value)
                {
                    OnCatIDChanging(value);
                    ReportPropertyChanging("CatID");
                    _CatID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CatID");
                    OnCatIDChanged();
                }
            }
        }
        private global::System.Int64 _CatID;
        partial void OnCatIDChanging(global::System.Int64 value);
        partial void OnCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CatName
        {
            get
            {
                return _CatName;
            }
            set
            {
                OnCatNameChanging(value);
                ReportPropertyChanging("CatName");
                _CatName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CatName");
                OnCatNameChanged();
            }
        }
        private global::System.String _CatName;
        partial void OnCatNameChanging(global::System.String value);
        partial void OnCatNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CatPrio
        {
            get
            {
                return _CatPrio;
            }
            set
            {
                OnCatPrioChanging(value);
                ReportPropertyChanging("CatPrio");
                _CatPrio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatPrio");
                OnCatPrioChanged();
            }
        }
        private Nullable<global::System.Int64> _CatPrio;
        partial void OnCatPrioChanging(Nullable<global::System.Int64> value);
        partial void OnCatPrioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CatDesc
        {
            get
            {
                return _CatDesc;
            }
            set
            {
                OnCatDescChanging(value);
                ReportPropertyChanging("CatDesc");
                _CatDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CatDesc");
                OnCatDescChanged();
            }
        }
        private global::System.String _CatDesc;
        partial void OnCatDescChanging(global::System.String value);
        partial void OnCatDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TempID
        {
            get
            {
                return _TempID;
            }
            set
            {
                OnTempIDChanging(value);
                ReportPropertyChanging("TempID");
                _TempID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TempID");
                OnTempIDChanged();
            }
        }
        private global::System.Int64 _TempID;
        partial void OnTempIDChanging(global::System.Int64 value);
        partial void OnTempIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Categories_Templates", "Templates")]
        public Template Template
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Template>("cms_2Model.FK_Categories_Templates", "Templates").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Template>("cms_2Model.FK_Categories_Templates", "Templates").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Template> TemplateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Template>("cms_2Model.FK_Categories_Templates", "Templates");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Template>("cms_2Model.FK_Categories_Templates", "Templates", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_CategoryRelations_Categories", "CategoryRelation")]
        public EntityCollection<CategoryRelation> CategoryRelations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CategoryRelation>("cms_2Model.FK_CategoryRelations_Categories", "CategoryRelation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CategoryRelation>("cms_2Model.FK_CategoryRelations_Categories", "CategoryRelation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_CategoryRelations_Categories1", "CategoryRelation")]
        public EntityCollection<CategoryRelation> CategoryRelations1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CategoryRelation>("cms_2Model.FK_CategoryRelations_Categories1", "CategoryRelation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CategoryRelation>("cms_2Model.FK_CategoryRelations_Categories1", "CategoryRelation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Links_Categories", "Link")]
        public EntityCollection<Link> Links
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Link>("cms_2Model.FK_Links_Categories", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Link>("cms_2Model.FK_Links_Categories", "Link", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Pictures_Categories", "Picture")]
        public EntityCollection<Picture> Pictures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Picture>("cms_2Model.FK_Pictures_Categories", "Picture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Picture>("cms_2Model.FK_Pictures_Categories", "Picture", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Texts_Categories", "Text")]
        public EntityCollection<Text> Texts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Text>("cms_2Model.FK_Texts_Categories", "Text");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Text>("cms_2Model.FK_Texts_Categories", "Text", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Videos_Categories", "Video")]
        public EntityCollection<Video> Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Video>("cms_2Model.FK_Videos_Categories", "Video");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Video>("cms_2Model.FK_Videos_Categories", "Video", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="CategoryRelation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoryRelation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoryRelation object.
        /// </summary>
        /// <param name="categoryRelationId">Initial value of the CategoryRelationId property.</param>
        /// <param name="parentCatID">Initial value of the ParentCatID property.</param>
        /// <param name="childCatID">Initial value of the ChildCatID property.</param>
        public static CategoryRelation CreateCategoryRelation(global::System.Int64 categoryRelationId, global::System.Int64 parentCatID, global::System.Int64 childCatID)
        {
            CategoryRelation categoryRelation = new CategoryRelation();
            categoryRelation.CategoryRelationId = categoryRelationId;
            categoryRelation.ParentCatID = parentCatID;
            categoryRelation.ChildCatID = childCatID;
            return categoryRelation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CategoryRelationId
        {
            get
            {
                return _CategoryRelationId;
            }
            set
            {
                if (_CategoryRelationId != value)
                {
                    OnCategoryRelationIdChanging(value);
                    ReportPropertyChanging("CategoryRelationId");
                    _CategoryRelationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryRelationId");
                    OnCategoryRelationIdChanged();
                }
            }
        }
        private global::System.Int64 _CategoryRelationId;
        partial void OnCategoryRelationIdChanging(global::System.Int64 value);
        partial void OnCategoryRelationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ParentCatID
        {
            get
            {
                return _ParentCatID;
            }
            set
            {
                OnParentCatIDChanging(value);
                ReportPropertyChanging("ParentCatID");
                _ParentCatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentCatID");
                OnParentCatIDChanged();
            }
        }
        private global::System.Int64 _ParentCatID;
        partial void OnParentCatIDChanging(global::System.Int64 value);
        partial void OnParentCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ChildCatID
        {
            get
            {
                return _ChildCatID;
            }
            set
            {
                OnChildCatIDChanging(value);
                ReportPropertyChanging("ChildCatID");
                _ChildCatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChildCatID");
                OnChildCatIDChanged();
            }
        }
        private global::System.Int64 _ChildCatID;
        partial void OnChildCatIDChanging(global::System.Int64 value);
        partial void OnChildCatIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_CategoryRelations_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_CategoryRelations_Categories1", "Category")]
        public Category Category1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories1", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories1", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> Category1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories1", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("cms_2Model.FK_CategoryRelations_Categories1", "Category", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="Link")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Link : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Link object.
        /// </summary>
        /// <param name="linkID">Initial value of the LinkID property.</param>
        /// <param name="linkUrl">Initial value of the LinkUrl property.</param>
        public static Link CreateLink(global::System.Int64 linkID, global::System.String linkUrl)
        {
            Link link = new Link();
            link.LinkID = linkID;
            link.LinkUrl = linkUrl;
            return link;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 LinkID
        {
            get
            {
                return _LinkID;
            }
            set
            {
                if (_LinkID != value)
                {
                    OnLinkIDChanging(value);
                    ReportPropertyChanging("LinkID");
                    _LinkID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LinkID");
                    OnLinkIDChanged();
                }
            }
        }
        private global::System.Int64 _LinkID;
        partial void OnLinkIDChanging(global::System.Int64 value);
        partial void OnLinkIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkTitle
        {
            get
            {
                return _LinkTitle;
            }
            set
            {
                OnLinkTitleChanging(value);
                ReportPropertyChanging("LinkTitle");
                _LinkTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkTitle");
                OnLinkTitleChanged();
            }
        }
        private global::System.String _LinkTitle;
        partial void OnLinkTitleChanging(global::System.String value);
        partial void OnLinkTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LinkUrl
        {
            get
            {
                return _LinkUrl;
            }
            set
            {
                OnLinkUrlChanging(value);
                ReportPropertyChanging("LinkUrl");
                _LinkUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LinkUrl");
                OnLinkUrlChanged();
            }
        }
        private global::System.String _LinkUrl;
        partial void OnLinkUrlChanging(global::System.String value);
        partial void OnLinkUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkText
        {
            get
            {
                return _LinkText;
            }
            set
            {
                OnLinkTextChanging(value);
                ReportPropertyChanging("LinkText");
                _LinkText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkText");
                OnLinkTextChanged();
            }
        }
        private global::System.String _LinkText;
        partial void OnLinkTextChanging(global::System.String value);
        partial void OnLinkTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LinkPrio
        {
            get
            {
                return _LinkPrio;
            }
            set
            {
                OnLinkPrioChanging(value);
                ReportPropertyChanging("LinkPrio");
                _LinkPrio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LinkPrio");
                OnLinkPrioChanged();
            }
        }
        private Nullable<global::System.Int64> _LinkPrio;
        partial void OnLinkPrioChanging(Nullable<global::System.Int64> value);
        partial void OnLinkPrioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CatID
        {
            get
            {
                return _CatID;
            }
            set
            {
                OnCatIDChanging(value);
                ReportPropertyChanging("CatID");
                _CatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatID");
                OnCatIDChanged();
            }
        }
        private Nullable<global::System.Int64> _CatID;
        partial void OnCatIDChanging(Nullable<global::System.Int64> value);
        partial void OnCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] LinkDateCreated
        {
            get
            {
                return StructuralObject.GetValidValue(_LinkDateCreated);
            }
            set
            {
                OnLinkDateCreatedChanging(value);
                ReportPropertyChanging("LinkDateCreated");
                _LinkDateCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkDateCreated");
                OnLinkDateCreatedChanged();
            }
        }
        private global::System.Byte[] _LinkDateCreated;
        partial void OnLinkDateCreatedChanging(global::System.Byte[] value);
        partial void OnLinkDateCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Links_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Links_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Links_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Links_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("cms_2Model.FK_Links_Categories", "Category", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="Picture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Picture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Picture object.
        /// </summary>
        /// <param name="picID">Initial value of the PicID property.</param>
        /// <param name="picUrl">Initial value of the PicUrl property.</param>
        /// <param name="picAltText">Initial value of the PicAltText property.</param>
        public static Picture CreatePicture(global::System.Int64 picID, global::System.String picUrl, global::System.String picAltText)
        {
            Picture picture = new Picture();
            picture.PicID = picID;
            picture.PicUrl = picUrl;
            picture.PicAltText = picAltText;
            return picture;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PicID
        {
            get
            {
                return _PicID;
            }
            set
            {
                if (_PicID != value)
                {
                    OnPicIDChanging(value);
                    ReportPropertyChanging("PicID");
                    _PicID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PicID");
                    OnPicIDChanged();
                }
            }
        }
        private global::System.Int64 _PicID;
        partial void OnPicIDChanging(global::System.Int64 value);
        partial void OnPicIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PicTitle
        {
            get
            {
                return _PicTitle;
            }
            set
            {
                OnPicTitleChanging(value);
                ReportPropertyChanging("PicTitle");
                _PicTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PicTitle");
                OnPicTitleChanged();
            }
        }
        private global::System.String _PicTitle;
        partial void OnPicTitleChanging(global::System.String value);
        partial void OnPicTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PicUrl
        {
            get
            {
                return _PicUrl;
            }
            set
            {
                OnPicUrlChanging(value);
                ReportPropertyChanging("PicUrl");
                _PicUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PicUrl");
                OnPicUrlChanged();
            }
        }
        private global::System.String _PicUrl;
        partial void OnPicUrlChanging(global::System.String value);
        partial void OnPicUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PicAltText
        {
            get
            {
                return _PicAltText;
            }
            set
            {
                OnPicAltTextChanging(value);
                ReportPropertyChanging("PicAltText");
                _PicAltText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PicAltText");
                OnPicAltTextChanged();
            }
        }
        private global::System.String _PicAltText;
        partial void OnPicAltTextChanging(global::System.String value);
        partial void OnPicAltTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PicDesc
        {
            get
            {
                return _PicDesc;
            }
            set
            {
                OnPicDescChanging(value);
                ReportPropertyChanging("PicDesc");
                _PicDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PicDesc");
                OnPicDescChanged();
            }
        }
        private global::System.String _PicDesc;
        partial void OnPicDescChanging(global::System.String value);
        partial void OnPicDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PicPrio
        {
            get
            {
                return _PicPrio;
            }
            set
            {
                OnPicPrioChanging(value);
                ReportPropertyChanging("PicPrio");
                _PicPrio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PicPrio");
                OnPicPrioChanged();
            }
        }
        private Nullable<global::System.Int64> _PicPrio;
        partial void OnPicPrioChanging(Nullable<global::System.Int64> value);
        partial void OnPicPrioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CatID
        {
            get
            {
                return _CatID;
            }
            set
            {
                OnCatIDChanging(value);
                ReportPropertyChanging("CatID");
                _CatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatID");
                OnCatIDChanged();
            }
        }
        private Nullable<global::System.Int64> _CatID;
        partial void OnCatIDChanging(Nullable<global::System.Int64> value);
        partial void OnCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] PicDateCreated
        {
            get
            {
                return StructuralObject.GetValidValue(_PicDateCreated);
            }
            set
            {
                OnPicDateCreatedChanging(value);
                ReportPropertyChanging("PicDateCreated");
                _PicDateCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PicDateCreated");
                OnPicDateCreatedChanged();
            }
        }
        private global::System.Byte[] _PicDateCreated;
        partial void OnPicDateCreatedChanging(global::System.Byte[] value);
        partial void OnPicDateCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Pictures_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Pictures_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Pictures_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Pictures_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("cms_2Model.FK_Pictures_Categories", "Category", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="Template")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Template : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Template object.
        /// </summary>
        /// <param name="tempID">Initial value of the TempID property.</param>
        /// <param name="tempName">Initial value of the TempName property.</param>
        /// <param name="tempDesc">Initial value of the TempDesc property.</param>
        /// <param name="tempURL">Initial value of the TempURL property.</param>
        public static Template CreateTemplate(global::System.Int64 tempID, global::System.String tempName, global::System.String tempDesc, global::System.String tempURL)
        {
            Template template = new Template();
            template.TempID = tempID;
            template.TempName = tempName;
            template.TempDesc = tempDesc;
            template.TempURL = tempURL;
            return template;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TempID
        {
            get
            {
                return _TempID;
            }
            set
            {
                if (_TempID != value)
                {
                    OnTempIDChanging(value);
                    ReportPropertyChanging("TempID");
                    _TempID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TempID");
                    OnTempIDChanged();
                }
            }
        }
        private global::System.Int64 _TempID;
        partial void OnTempIDChanging(global::System.Int64 value);
        partial void OnTempIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TempName
        {
            get
            {
                return _TempName;
            }
            set
            {
                OnTempNameChanging(value);
                ReportPropertyChanging("TempName");
                _TempName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TempName");
                OnTempNameChanged();
            }
        }
        private global::System.String _TempName;
        partial void OnTempNameChanging(global::System.String value);
        partial void OnTempNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TempDesc
        {
            get
            {
                return _TempDesc;
            }
            set
            {
                OnTempDescChanging(value);
                ReportPropertyChanging("TempDesc");
                _TempDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TempDesc");
                OnTempDescChanged();
            }
        }
        private global::System.String _TempDesc;
        partial void OnTempDescChanging(global::System.String value);
        partial void OnTempDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TempURL
        {
            get
            {
                return _TempURL;
            }
            set
            {
                OnTempURLChanging(value);
                ReportPropertyChanging("TempURL");
                _TempURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TempURL");
                OnTempURLChanged();
            }
        }
        private global::System.String _TempURL;
        partial void OnTempURLChanging(global::System.String value);
        partial void OnTempURLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Categories_Templates", "Categories")]
        public EntityCollection<Category> Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Category>("cms_2Model.FK_Categories_Templates", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Category>("cms_2Model.FK_Categories_Templates", "Categories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="Text")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Text : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Text object.
        /// </summary>
        /// <param name="textID">Initial value of the TextID property.</param>
        /// <param name="textData">Initial value of the TextData property.</param>
        public static Text CreateText(global::System.Int64 textID, global::System.String textData)
        {
            Text text = new Text();
            text.TextID = textID;
            text.TextData = textData;
            return text;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TextID
        {
            get
            {
                return _TextID;
            }
            set
            {
                if (_TextID != value)
                {
                    OnTextIDChanging(value);
                    ReportPropertyChanging("TextID");
                    _TextID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TextID");
                    OnTextIDChanged();
                }
            }
        }
        private global::System.Int64 _TextID;
        partial void OnTextIDChanging(global::System.Int64 value);
        partial void OnTextIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TextTitle
        {
            get
            {
                return _TextTitle;
            }
            set
            {
                OnTextTitleChanging(value);
                ReportPropertyChanging("TextTitle");
                _TextTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TextTitle");
                OnTextTitleChanged();
            }
        }
        private global::System.String _TextTitle;
        partial void OnTextTitleChanging(global::System.String value);
        partial void OnTextTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TextData
        {
            get
            {
                return _TextData;
            }
            set
            {
                OnTextDataChanging(value);
                ReportPropertyChanging("TextData");
                _TextData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TextData");
                OnTextDataChanged();
            }
        }
        private global::System.String _TextData;
        partial void OnTextDataChanging(global::System.String value);
        partial void OnTextDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TextPrio
        {
            get
            {
                return _TextPrio;
            }
            set
            {
                OnTextPrioChanging(value);
                ReportPropertyChanging("TextPrio");
                _TextPrio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TextPrio");
                OnTextPrioChanged();
            }
        }
        private Nullable<global::System.Int64> _TextPrio;
        partial void OnTextPrioChanging(Nullable<global::System.Int64> value);
        partial void OnTextPrioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CatID
        {
            get
            {
                return _CatID;
            }
            set
            {
                OnCatIDChanging(value);
                ReportPropertyChanging("CatID");
                _CatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatID");
                OnCatIDChanged();
            }
        }
        private Nullable<global::System.Int64> _CatID;
        partial void OnCatIDChanging(Nullable<global::System.Int64> value);
        partial void OnCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] TextDateCreated
        {
            get
            {
                return StructuralObject.GetValidValue(_TextDateCreated);
            }
            set
            {
                OnTextDateCreatedChanging(value);
                ReportPropertyChanging("TextDateCreated");
                _TextDateCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TextDateCreated");
                OnTextDateCreatedChanged();
            }
        }
        private global::System.Byte[] _TextDateCreated;
        partial void OnTextDateCreatedChanging(global::System.Byte[] value);
        partial void OnTextDateCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Texts_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Texts_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Texts_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Texts_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("cms_2Model.FK_Texts_Categories", "Category", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cms_2Model", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="vidID">Initial value of the VidID property.</param>
        /// <param name="vidUrl">Initial value of the VidUrl property.</param>
        public static Video CreateVideo(global::System.Int64 vidID, global::System.String vidUrl)
        {
            Video video = new Video();
            video.VidID = vidID;
            video.VidUrl = vidUrl;
            return video;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 VidID
        {
            get
            {
                return _VidID;
            }
            set
            {
                if (_VidID != value)
                {
                    OnVidIDChanging(value);
                    ReportPropertyChanging("VidID");
                    _VidID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VidID");
                    OnVidIDChanged();
                }
            }
        }
        private global::System.Int64 _VidID;
        partial void OnVidIDChanging(global::System.Int64 value);
        partial void OnVidIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VidTitle
        {
            get
            {
                return _VidTitle;
            }
            set
            {
                OnVidTitleChanging(value);
                ReportPropertyChanging("VidTitle");
                _VidTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VidTitle");
                OnVidTitleChanged();
            }
        }
        private global::System.String _VidTitle;
        partial void OnVidTitleChanging(global::System.String value);
        partial void OnVidTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VidUrl
        {
            get
            {
                return _VidUrl;
            }
            set
            {
                OnVidUrlChanging(value);
                ReportPropertyChanging("VidUrl");
                _VidUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VidUrl");
                OnVidUrlChanged();
            }
        }
        private global::System.String _VidUrl;
        partial void OnVidUrlChanging(global::System.String value);
        partial void OnVidUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VidDesc
        {
            get
            {
                return _VidDesc;
            }
            set
            {
                OnVidDescChanging(value);
                ReportPropertyChanging("VidDesc");
                _VidDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VidDesc");
                OnVidDescChanged();
            }
        }
        private global::System.String _VidDesc;
        partial void OnVidDescChanging(global::System.String value);
        partial void OnVidDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> VidPrio
        {
            get
            {
                return _VidPrio;
            }
            set
            {
                OnVidPrioChanging(value);
                ReportPropertyChanging("VidPrio");
                _VidPrio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VidPrio");
                OnVidPrioChanged();
            }
        }
        private Nullable<global::System.Int64> _VidPrio;
        partial void OnVidPrioChanging(Nullable<global::System.Int64> value);
        partial void OnVidPrioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CatID
        {
            get
            {
                return _CatID;
            }
            set
            {
                OnCatIDChanging(value);
                ReportPropertyChanging("CatID");
                _CatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatID");
                OnCatIDChanged();
            }
        }
        private Nullable<global::System.Int64> _CatID;
        partial void OnCatIDChanging(Nullable<global::System.Int64> value);
        partial void OnCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] VidDateCreated
        {
            get
            {
                return StructuralObject.GetValidValue(_VidDateCreated);
            }
            set
            {
                OnVidDateCreatedChanging(value);
                ReportPropertyChanging("VidDateCreated");
                _VidDateCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VidDateCreated");
                OnVidDateCreatedChanged();
            }
        }
        private global::System.Byte[] _VidDateCreated;
        partial void OnVidDateCreatedChanging(global::System.Byte[] value);
        partial void OnVidDateCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cms_2Model", "FK_Videos_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Videos_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Videos_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("cms_2Model.FK_Videos_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("cms_2Model.FK_Videos_Categories", "Category", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
